# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Country(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, code: str=None, currency_id: int=None, active: bool=True):  # noqa: E501
        """Country - a model defined in Swagger

        :param id: The id of this Country.  # noqa: E501
        :type id: int
        :param name: The name of this Country.  # noqa: E501
        :type name: str
        :param code: The code of this Country.  # noqa: E501
        :type code: str
        :param currency_id: The currency_id of this Country.  # noqa: E501
        :type currency_id: int
        :param active: The active of this Country.  # noqa: E501
        :type active: bool
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'code': str,
            'currency_id': int,
            'active': bool
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'code': 'code',
            'currency_id': 'currency_id',
            'active': 'active'
        }
        self._id = id
        self._name = name
        self._code = code
        self._currency_id = currency_id
        self._active = active

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Country.


        :return: The id of this Country.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Country.


        :param id: The id of this Country.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Country.


        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Country.


        :param name: The name of this Country.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def code(self) -> str:
        """Gets the code of this Country.


        :return: The code of this Country.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Country.


        :param code: The code of this Country.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def currency_id(self) -> int:
        """Gets the currency_id of this Country.


        :return: The currency_id of this Country.
        :rtype: int
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id: int):
        """Sets the currency_id of this Country.


        :param currency_id: The currency_id of this Country.
        :type currency_id: int
        """

        self._currency_id = currency_id

    @property
    def active(self) -> bool:
        """Gets the active of this Country.


        :return: The active of this Country.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Country.


        :param active: The active of this Country.
        :type active: bool
        """

        self._active = active
